project:
  type: website
  render:
  - '*.qmd'
  - '*.ipynb'
  - 'examples/*.ipynb'
  - 'pages/*.qmd'
  resources:
  - assets/*
  - authors.yml
  - CITATION.cff
execute:
  freeze: auto
website:
  favicon: "assets/logo_white.png"
  twitter-card: true
  open-graph: true
  navbar:
    collapse-below: xl
    pinned: false
    title: false
    left:
    - text: '{{< iconify qlementine-icons:version-control-16 >}}'
      menu:
      - text: v01 (latest)
        href: index.ipynb
    - text: '{{< iconify nrk:back >}} Back to Pub'
      href: index.ipynb
    - text: Demo
      href: /examples/demo.html
    right:
    - text: FAQ
      href: pages/FAQ.qmd
    - text: Reproduce this pub
      href: pages/SETUP.qmd
    - text: Cite this pub
      href: "#"
    - text: Contribute
      href: pages/CONTRIBUTING.qmd
    tools:
    - icon: twitter-x
      href: https://twitter.com/arcadiascience
    - icon: github
      href: https://github.com/{{< var pub.org >}}/{{< var pub.repo >}}
    logo: assets/logo_text.png
    logo-href: https://research.arcadiascience.com/
    background: white
    search: true
  page-footer:
    background: '#484B50'
    border: false
    left: '[![](/assets/logo_white.png){fig-alt="Arcadia-Science" width=65px}](https://www.arcadiascience.com/)

      Copyright 2025, Arcadia Science

      '
    right:
    - icon: twitter-x
      href: https://twitter.com/arcadiascience
    - icon: github
      href: https://github.com/Arcadia-Science
  google-analytics: '{{< var pub.google_analytics_id >}}'
  cookie-consent:
    type: implied
    style: simple
format:
  html:
    include-in-header:
    - file: assets/logo-animation.html
    - file: assets/author-reveal.html
    - file: assets/mini-title.html
    - file: assets/version-in-title.html
    - file: assets/citation-box.html
    css: 
    - assets/css/main.css
    - assets/css/citation-box.css
    page-layout: article
    title-block-banner: true
    toc: true
    toc-expand: 2
comments:
  giscus:
    repo: Arcadia-Science/notebook-pub-template
    input-position: top
reference-location: margin
bibliography: ref.bib
csl: assets/arcadia.csl
code-annotations: hover
html-table-processing: none
filters:
- abstract-section
demo-title: A brief syntax demo
